chore: success or failure

diff --git a/.github/workflows/deploy-manual.yml b/.github/workflows/deploy-manual.yml
--- a/.github/workflows/deploy-manual.yml
+++ b/.github/workflows/deploy-manual.yml
@@ -67,3 +67,7 @@ jobs:
       - name: (debug) success()
         if: success()
         run: echo "running success"
+
+      - name: (debug) success() || failure()
+        if: success() || failure()
+        run: echo "running for ${{ success() && 'success' || 'failure' }}"
